In [1]:
from __future__ import division
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr, spearmanr, probplot
%matplotlib inline

## 1) Loading the Data

In [2]:
print("Load the training, test and store data using pandas")
train = pd.read_csv("input/train.csv")
test = pd.read_csv("input/test.csv")
store = pd.read_csv("input/store.csv")
states = pd.read_csv("../../data/store_states.csv")  # stores per state from https://www.kaggle.com/c/rossmann-store-sales/forums/t/17048/putting-stores-on-the-map/

Load the training, test and store data using pandas


/Users/2015/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
train.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1            0   
1      2          5  2015-07-31   6064        625     1      1            0   
2      3          5  2015-07-31   8314        821     1      1            0   
3      4          5  2015-07-31  13995       1498     1      1            0   
4      5          5  2015-07-31   4822        559     1      1            0   

   SchoolHoliday  
0              1  
1              1  
2              1  
3              1  
4              1

In [4]:
test.head()

Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17     1      1            0              0
1   2      3          4  2015-09-17     1      1            0              0
2   3      7          4  2015-09-17     1      1            0              0
3   4      8          4  2015-09-17     1      1            0              0
4   5      9          4  2015-09-17     1      1            0              0

In [5]:
store.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a                 1270                          9   
1      2         a          a                  570                         11   
2      3         a          a                14130                         12   
3      4         c          c                  620                          9   
4      5         a          a                29910                          4   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                      2008       0              NaN              NaN   
1                      2007       1               13             2010   
2                      2006       1               14             2011   
3                      2009       0              NaN              NaN   
4                      2015       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct  
3              NaN  
4              NaN

In [6]:
states.head()

Store State
0      1    HE
1      2    TH
2      3    NW
3      4    BE
4      5    SN

# Exploring the data

In [7]:
train.describe()

Store       DayOfWeek           Sales       Customers  \
count  1017209.000000  1017209.000000  1017209.000000  1017209.000000   
mean       558.429727        3.998341     5773.818972      633.145946   
std        321.908651        1.997391     3849.926175      464.411734   
min          1.000000        1.000000        0.000000        0.000000   
25%        280.000000        2.000000     3727.000000      405.000000   
50%        558.000000        4.000000     5744.000000      609.000000   
75%        838.000000        6.000000     7856.000000      837.000000   
max       1115.000000        7.000000    41551.000000     7388.000000   

                 Open           Promo   SchoolHoliday  
count  1017209.000000  1017209.000000  1017209.000000  
mean         0.830107        0.381515        0.178647  
std          0.375539        0.485759        0.383056  
min          0.000000        0.000000        0.000000  
25%          1.000000        0.000000        0.000000  
50%          1.000000        0.000000        0.000000  
75%          1.000000        1.000000        0.000000  
max          1.000000        1.000000        1.000000

In [8]:
test.describe()

Id         Store     DayOfWeek          Open         Promo  \
count  41088.000000  41088.000000  41088.000000  41077.000000  41088.000000   
mean   20544.500000    555.899533      3.979167      0.854322      0.395833   
std    11861.228267    320.274496      2.015481      0.352787      0.489035   
min        1.000000      1.000000      1.000000      0.000000      0.000000   
25%    10272.750000    279.750000      2.000000      1.000000      0.000000   
50%    20544.500000    553.500000      4.000000      1.000000      0.000000   
75%    30816.250000    832.250000      6.000000      1.000000      1.000000   
max    41088.000000   1115.000000      7.000000      1.000000      1.000000   

       SchoolHoliday  
count   41088.000000  
mean        0.443487  
std         0.496802  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [9]:
store.describe()

Store  CompetitionDistance  CompetitionOpenSinceMonth  \
count  1115.00000          1112.000000                 761.000000   
mean    558.00000          5404.901079                   7.224704   
std     322.01708          7663.174720                   3.212348   
min       1.00000            20.000000                   1.000000   
25%     279.50000           717.500000                   4.000000   
50%     558.00000          2325.000000                   8.000000   
75%     836.50000          6882.500000                  10.000000   
max    1115.00000         75860.000000                  12.000000   

       CompetitionOpenSinceYear       Promo2  Promo2SinceWeek  Promo2SinceYear  
count                761.000000  1115.000000       571.000000       571.000000  
mean                2008.668857     0.512108        23.595447      2011.763573  
std                    6.195983     0.500078        14.141984         1.674935  
min                 1900.000000     0.000000         1.000000      2009.000000  
25%                 2006.000000     0.000000        13.000000      2011.000000  
50%                 2010.000000     1.000000        22.000000      2012.000000  
75%                 2013.000000     1.000000        37.000000      2013.000000  
max                 2015.000000     1.000000        50.000000      2015.000000

# Missing Values

In [10]:
pd.isnull(train).any()

Store            False
DayOfWeek        False
Date             False
Sales            False
Customers        False
Open             False
Promo            False
StateHoliday     False
SchoolHoliday    False
dtype: bool

In [11]:
pd.isnull(test).any()

Id               False
Store            False
DayOfWeek        False
Date             False
Open              True
Promo            False
StateHoliday     False
SchoolHoliday    False
dtype: bool

In [12]:
pd.isnull(store).any()

Store                        False
StoreType                    False
Assortment                   False
CompetitionDistance           True
CompetitionOpenSinceMonth     True
CompetitionOpenSinceYear      True
Promo2                       False
Promo2SinceWeek               True
Promo2SinceYear               True
PromoInterval                 True
dtype: bool

In [13]:
pd.isnull(states).any()

Store    False
State    False
dtype: bool

In [14]:
test[test.isnull().any(axis=1)]

Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  \
479      480    622          4  2015-09-17   NaN      1            0   
1335    1336    622          3  2015-09-16   NaN      1            0   
2191    2192    622          2  2015-09-15   NaN      1            0   
3047    3048    622          1  2015-09-14   NaN      1            0   
4759    4760    622          6  2015-09-12   NaN      0            0   
5615    5616    622          5  2015-09-11   NaN      0            0   
6471    6472    622          4  2015-09-10   NaN      0            0   
7327    7328    622          3  2015-09-09   NaN      0            0   
8183    8184    622          2  2015-09-08   NaN      0            0   
9039    9040    622          1  2015-09-07   NaN      0            0   
10751  10752    622          6  2015-09-05   NaN      0            0   

       SchoolHoliday  
479                0  
1335               0  
2191               0  
3047               0  
4759               0  
5615               0  
6471               0  
7327               0  
8183               0  
9039               0  
10751              0

**Only store 622 has NaN for Open feature in the test set**

In [15]:
test.loc[test['Store'] == 622]

Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  \
479      480    622          4  2015-09-17   NaN      1            0   
1335    1336    622          3  2015-09-16   NaN      1            0   
2191    2192    622          2  2015-09-15   NaN      1            0   
3047    3048    622          1  2015-09-14   NaN      1            0   
3903    3904    622          7  2015-09-13     0      0            0   
4759    4760    622          6  2015-09-12   NaN      0            0   
5615    5616    622          5  2015-09-11   NaN      0            0   
6471    6472    622          4  2015-09-10   NaN      0            0   
7327    7328    622          3  2015-09-09   NaN      0            0   
8183    8184    622          2  2015-09-08   NaN      0            0   
9039    9040    622          1  2015-09-07   NaN      0            0   
9895    9896    622          7  2015-09-06     0      0            0   
10751  10752    622          6  2015-09-05   NaN      0            0   
11607  11608    622          5  2015-09-04     1      1            0   
12463  12464    622          4  2015-09-03     1      1            0   
13319  13320    622          3  2015-09-02     1      1            0   
14175  14176    622          2  2015-09-01     1      1            0   
15031  15032    622          1  2015-08-31     1      1            0   
15887  15888    622          7  2015-08-30     0      0            0   
16743  16744    622          6  2015-08-29     1      0            0   
17599  17600    622          5  2015-08-28     1      0            0   
18455  18456    622          4  2015-08-27     1      0            0   
19311  19312    622          3  2015-08-26     1      0            0   
20167  20168    622          2  2015-08-25     1      0            0   
21023  21024    622          1  2015-08-24     1      0            0   
21879  21880    622          7  2015-08-23     0      0            0   
22735  22736    622          6  2015-08-22     1      0            0   
23591  23592    622          5  2015-08-21     1      1            0   
24447  24448    622          4  2015-08-20     1      1            0   
25303  25304    622          3  2015-08-19     1      1            0   
26159  26160    622          2  2015-08-18     1      1            0   
27015  27016    622          1  2015-08-17     1      1            0   
27871  27872    622          7  2015-08-16     0      0            0   
28727  28728    622          6  2015-08-15     1      0            0   
29583  29584    622          5  2015-08-14     1      0            0   
30439  30440    622          4  2015-08-13     1      0            0   
31295  31296    622          3  2015-08-12     1      0            0   
32151  32152    622          2  2015-08-11     1      0            0   
33007  33008    622          1  2015-08-10     1      0            0   
33863  33864    622          7  2015-08-09     0      0            0   
34719  34720    622          6  2015-08-08     1      0            0   
35575  35576    622          5  2015-08-07     1      1            0   
36431  36432    622          4  2015-08-06     1      1            0   
37287  37288    622          3  2015-08-05     1      1            0   
38143  38144    622          2  2015-08-04     1      1            0   
38999  39000    622          1  2015-08-03     1      1            0   
39855  39856    622          7  2015-08-02     0      0            0   
40711  40712    622          6  2015-08-01     1      0            0   

       SchoolHoliday  
479                0  
1335               0  
2191               0  
3047               0  
3903               0  
4759               0  
5615               0  
6471               0  
7327               0  
8183               0  
9039               0  
9895               0  
10751              0  
11607              0  
12463              0  
13319              0  
14175              0  
15031              0  
15887              0  
16743              0 

Store 622 has 11 missing values in the Open columns, but not all of the data in that column of that store is missing. Based upon the previous dates, Store 622 is closed on Sundays (Open = 0) and the rest of the dates fall on Monday to Saturday, so can impute Open = 1.

In [16]:
# Impute Open = 1 for store 622
test['Open'].fillna(1, inplace=True)

# Separating the Date column into Features

In [17]:
from numpy import double
#Separating the date columns
train['year'] = train.Date.apply(lambda x: x.split('-')[0])
train['year'] = train['year'].astype(double)
train['month'] = train.Date.apply(lambda x: x.split('-')[1])
train['month'] = train['month'].astype(double)
train['day'] = train.Date.apply(lambda x: x.split('-')[2])
train['day'] = train['day'].astype(double)

In [18]:
train.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1            0   
1      2          5  2015-07-31   6064        625     1      1            0   
2      3          5  2015-07-31   8314        821     1      1            0   
3      4          5  2015-07-31  13995       1498     1      1            0   
4      5          5  2015-07-31   4822        559     1      1            0   

   SchoolHoliday  year  month  day  
0              1  2015      7   31  
1              1  2015      7   31  
2              1  2015      7   31  
3              1  2015      7   31  
4              1  2015      7   31

# Add additional Date columns

* day_of_year
* weekofyear
* quarter
* is_month_start
* is_month_end
* is_quarter_start
* is_quarter_end

In [19]:
# create test data frame first
df = train

In [20]:
df['Date'] = pd.to_datetime(df['Date'])

In [21]:
import datetime
df['day_of_year'] = df['Date'].dt.dayofyear
df['weekofyear'] = df['Date'].dt.weekofyear
df['quarter'] = df['Date'].dt.quarter
df['is_month_start'] = df['Date'].dt.is_month_start.astype(int)
df['is_month_end'] = df['Date'].dt.is_month_end.astype(int)
df['is_quarter_start'] = df['Date'].dt.is_quarter_start.astype(int)
df['is_quarter_end'] = df['Date'].dt.is_quarter_end.astype(int)

In [22]:
df.head()

Store  DayOfWeek       Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5 2015-07-31   5263        555     1      1            0   
1      2          5 2015-07-31   6064        625     1      1            0   
2      3          5 2015-07-31   8314        821     1      1            0   
3      4          5 2015-07-31  13995       1498     1      1            0   
4      5          5 2015-07-31   4822        559     1      1            0   

   SchoolHoliday  year  month  day  day_of_year  weekofyear  quarter  \
0              1  2015      7   31          212          31        3   
1              1  2015      7   31          212          31        3   
2              1  2015      7   31          212          31        3   
3              1  2015      7   31          212          31        3   
4              1  2015      7   31          212          31        3   

   is_month_start  is_month_end  is_quarter_start  is_quarter_end  
0               0             1                 0               0  
1               0             1                 0               0  
2               0             1                 0               0  
3               0             1                 0               0  
4               0             1                 0               0

In [23]:
df.loc[(df['Open'] == 1) & ((df['Sales'] == 0) | (df['Customers'] == 0))].shape

(54, 19)

**54 stores have a day when they are listed as Open but no Sales and/or No customers. It sppears that this is the day before the re-open after being refurbished. Can safely be set to 0**

In [24]:
df.ix[(df['Open'] == 1) & ((df['Sales'] == 0) | (df['Customers'] == 0))] = 0

In [25]:
# confirm that Open has been set to 0 for stores with Open=1 and no sales and no customers
df.loc[(df['Open'] == 1) & ((df['Sales'] == 0) | (df['Customers'] == 0))].shape

(0, 19)

In [26]:
# now add date features to train data set
train['Date'] = pd.to_datetime(train['Date'])

In [27]:
train['day_of_year'] = train['Date'].dt.dayofyear
train['weekofyear'] = train['Date'].dt.weekofyear
train['quarter'] = train['Date'].dt.quarter
train['is_month_start'] = train['Date'].dt.is_month_start.astype(int)
train['is_month_end'] = train['Date'].dt.is_month_end.astype(int)
train['is_quarter_start'] = train['Date'].dt.is_quarter_start.astype(int)
train['is_quarter_end'] = train['Date'].dt.is_quarter_end.astype(int)

In [28]:
train.head()

Store  DayOfWeek       Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5 2015-07-31   5263        555     1      1            0   
1      2          5 2015-07-31   6064        625     1      1            0   
2      3          5 2015-07-31   8314        821     1      1            0   
3      4          5 2015-07-31  13995       1498     1      1            0   
4      5          5 2015-07-31   4822        559     1      1            0   

   SchoolHoliday  year  month  day  day_of_year  weekofyear  quarter  \
0              1  2015      7   31          212          31        3   
1              1  2015      7   31          212          31        3   
2              1  2015      7   31          212          31        3   
3              1  2015      7   31          212          31        3   
4              1  2015      7   31          212          31        3   

   is_month_start  is_month_end  is_quarter_start  is_quarter_end  
0               0             1                 0               0  
1               0             1                 0               0  
2               0             1                 0               0  
3               0             1                 0               0  
4               0             1                 0               0

In [29]:
# check how many stores are listed as Open but have 0 sales and/or 0 customers
train.loc[(train['Open'] == 1) & ((train['Sales'] == 0) | (train['Customers'] == 0))].shape

(0, 19)

In [30]:
train.ix[(train['Open'] == 1) & ((train['Sales'] == 0) | (train['Customers'] == 0))] = 0

In [31]:
# check how many stores are listed as Open but have 0 sales and/or 0 customers
train.loc[(train['Open'] == 1) & ((train['Sales'] == 0) | (train['Customers'] == 0))].shape

(0, 19)

# State Holidays

In [32]:
df.loc[(df['Store'] == 674) & (df['Open'] == 0) & (df['StateHoliday'] == 'b')].sort(['Store', 'Date'])

/Users/2015/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


Store  DayOfWeek       Date  Sales  Customers  Open  Promo  \
919763    674          5 2013-03-29      0          0     0      1   
916418    674          1 2013-04-01      0          0     0      0   
490488    674          5 2014-04-18      0          0     0      1   
487143    674          1 2014-04-21      0          0     0      0   
133358    674          5 2015-04-03      0          0     0      1   
130013    674          1 2015-04-06      0          0     0      0   

       StateHoliday  SchoolHoliday  year  month  day  day_of_year  weekofyear  \
919763            b              1  2013      3   29           88          13   
916418            b              1  2013      4    1           91          14   
490488            b              1  2014      4   18          108          16   
487143            b              1  2014      4   21          111          17   
133358            b              1  2015      4    3           93          14   
130013            b              1  2015      4    6           96          15   

        quarter  is_month_start  is_month_end  is_quarter_start  \
919763        1               0             0                 0   
916418        2               1             0                 1   
490488        2               0             0                 0   
487143        2               0             0                 0   
133358        2               0             0                 0   
130013        2               0             0                 0   

        is_quarter_end  
919763               0  
916418               0  
490488               0  
487143               0  
133358               0  
130013               0

* 'a' seems to be a pretty general category for State Holiday
* 'b' looks to be Easter. A cursory glance doesn't reveal any spike in spending but need to confirm
* 'c' is Christmas. What about Days before Christmas column?
* Is O being used as a string and an integer

In [33]:
pd.unique(df.StateHoliday.ravel())

array(['0', 'a', 0, 'b', 'c'], dtype=object)

**Yes, it is being treated as both an integer and string. Need to convert**

In [34]:
# Convert on test data frame first
df.ix[(df['StateHoliday'] == 0)] = '0'

In [35]:
pd.unique(df.StateHoliday.ravel())

array(['0', 'a', 'b', 'c'], dtype=object)

In [36]:
# Convert on train data frame
train.ix[(train['StateHoliday'] == 0)] = '0'

# Add First Day of Promo feature

In [37]:
# Test on df data frame first
df['PromoFirstDate'] = 0

In [38]:
df.head()

Store DayOfWeek       Date  Sales Customers Open Promo StateHoliday  \
0     1         5 2015-07-31   5263       555    1     1            0   
1     2         5 2015-07-31   6064       625    1     1            0   
2     3         5 2015-07-31   8314       821    1     1            0   
3     4         5 2015-07-31  13995      1498    1     1            0   
4     5         5 2015-07-31   4822       559    1     1            0   

  SchoolHoliday  year month day day_of_year weekofyear quarter is_month_start  \
0             1  2015     7  31         212         31       3              0   
1             1  2015     7  31         212         31       3              0   
2             1  2015     7  31         212         31       3              0   
3             1  2015     7  31         212         31       3              0   
4             1  2015     7  31         212         31       3              0   

  is_month_end is_quarter_start is_quarter_end  PromoFirstDate  
0            1                0              0               0  
1            1                0              0               0  
2            1                0              0               0  
3            1                0              0               0  
4            1                0              0               0

## Need to sort data frame first (by store and date)

In [39]:
# Test on df data frame first
df = df.sort_values(by=['Store', 'Date'], ascending=True,na_position='last')

In [47]:
df.head(15)

Store DayOfWeek       Date Sales Customers Open Promo StateHoliday  \
1016095     1         2 2013-01-01     0         0    0     0            a   
1014980     1         3 2013-01-02  5530       668    1     0            0   
1013865     1         4 2013-01-03  4327       578    1     0            0   
1012750     1         5 2013-01-04  4486       619    1     0            0   
1011635     1         6 2013-01-05  4997       635    1     0            0   
1010520     1         7 2013-01-06     0         0    0     0            0   
1009405     1         1 2013-01-07  7176       785    1     1            0   
1008290     1         2 2013-01-08  5580       654    1     1            0   
1007175     1         3 2013-01-09  5471       626    1     1            0   
1006060     1         4 2013-01-10  4892       615    1     1            0   
1004945     1         5 2013-01-11  4881       592    1     1            0   
1003830     1         6 2013-01-12  4952       646    1     0            0   
1002715     1         7 2013-01-13     0         0    0     0            0   
1001600     1         1 2013-01-14  4717       616    1     0            0   
1000485     1         2 2013-01-15  3900       512    1     0            0   

        SchoolHoliday  year month day day_of_year weekofyear quarter  \
1016095             1  2013     1   1           1          1       1   
1014980             1  2013     1   2           2          1       1   
1013865             1  2013     1   3           3          1       1   
1012750             1  2013     1   4           4          1       1   
1011635             1  2013     1   5           5          1       1   
1010520             1  2013     1   6           6          1       1   
1009405             1  2013     1   7           7          2       1   
1008290             1  2013     1   8           8          2       1   
1007175             1  2013     1   9           9          2       1   
1006060             1  2013     1  10          10          2       1   
1004945             1  2013     1  11          11          2       1   
1003830             0  2013     1  12          12          2       1   
1002715             0  2013     1  13          13          2       1   
1001600             0  2013     1  14          14          3       1   
1000485             0  2013     1  15          15          3       1   

        is_month_start is_month_end is_quarter_start is_quarter_end  \
1016095              1            0                1              0   
1014980              0            0                0              0   
1013865              0            0                0              0   
1012750              0            0                0              0   
1011635              0            0                0              0   
1010520              0            0                0              0   
1009405              0            0                0              0   
1008290              0            0                0              0   
1007175              0            0                0              0   
1006060              0            0                0              0   
1004945              0            0                0              0   
1003830              0            0                0              0   
1002715              0            0                0              0   
1001600              0            0                0              0   
1000485              0            0                0              0   

         PromoFirstDate  
1016095               0  
1014980               0  
1013865               0  
1012750               0  
1011635               0  
1010520               0  
1009405               1  
1008290               0  
1007175               0  
1006060               0  
1004945               0  
1003830               0  
1002715               0  
1001600               0  
1000485               0

**Set first day of Promo**

In [41]:
# set PromoFirstDate = 1 if Promo = 1 for current row and Promo = 0 for preceding row
df.ix[(df['Promo'] == 1 ) & (df['Promo'].shift(1) ==0), 'PromoFirstDate'] = 1

In [44]:
# glance at data frame to see if this worked correctly
df.head(10)

Store DayOfWeek       Date Sales Customers Open Promo StateHoliday  \
1016095     1         2 2013-01-01     0         0    0     0            a   
1014980     1         3 2013-01-02  5530       668    1     0            0   
1013865     1         4 2013-01-03  4327       578    1     0            0   
1012750     1         5 2013-01-04  4486       619    1     0            0   
1011635     1         6 2013-01-05  4997       635    1     0            0   
1010520     1         7 2013-01-06     0         0    0     0            0   
1009405     1         1 2013-01-07  7176       785    1     1            0   
1008290     1         2 2013-01-08  5580       654    1     1            0   
1007175     1         3 2013-01-09  5471       626    1     1            0   
1006060     1         4 2013-01-10  4892       615    1     1            0   

        SchoolHoliday  year month day day_of_year weekofyear quarter  \
1016095             1  2013     1   1           1          1       1   
1014980             1  2013     1   2           2          1       1   
1013865             1  2013     1   3           3          1       1   
1012750             1  2013     1   4           4          1       1   
1011635             1  2013     1   5           5          1       1   
1010520             1  2013     1   6           6          1       1   
1009405             1  2013     1   7           7          2       1   
1008290             1  2013     1   8           8          2       1   
1007175             1  2013     1   9           9          2       1   
1006060             1  2013     1  10          10          2       1   

        is_month_start is_month_end is_quarter_start is_quarter_end  \
1016095              1            0                1              0   
1014980              0            0                0              0   
1013865              0            0                0              0   
1012750              0            0                0              0   
1011635              0            0                0              0   
1010520              0            0                0              0   
1009405              0            0                0              0   
1008290              0            0                0              0   
1007175              0            0                0              0   
1006060              0            0                0              0   

         PromoFirstDate  
1016095               0  
1014980               0  
1013865               0  
1012750               0  
1011635               0  
1010520               0  
1009405               1  
1008290               0  
1007175               0  
1006060               0

In [45]:
# Now set PromoFirstDate = 1 for Train data frame
# first sort the data frame
train = train.sort_values(by=['Store', 'Date'], ascending=True,na_position='last')

In [48]:
train['PromoFirstDate'] = 0

In [49]:
# glance at data frame to see if this worked correctly
train.head(10)

Store DayOfWeek       Date Sales Customers Open Promo StateHoliday  \
1016095     1         2 2013-01-01     0         0    0     0            a   
1014980     1         3 2013-01-02  5530       668    1     0            0   
1013865     1         4 2013-01-03  4327       578    1     0            0   
1012750     1         5 2013-01-04  4486       619    1     0            0   
1011635     1         6 2013-01-05  4997       635    1     0            0   
1010520     1         7 2013-01-06     0         0    0     0            0   
1009405     1         1 2013-01-07  7176       785    1     1            0   
1008290     1         2 2013-01-08  5580       654    1     1            0   
1007175     1         3 2013-01-09  5471       626    1     1            0   
1006060     1         4 2013-01-10  4892       615    1     1            0   

        SchoolHoliday  year month day day_of_year weekofyear quarter  \
1016095             1  2013     1   1           1          1       1   
1014980             1  2013     1   2           2          1       1   
1013865             1  2013     1   3           3          1       1   
1012750             1  2013     1   4           4          1       1   
1011635             1  2013     1   5           5          1       1   
1010520             1  2013     1   6           6          1       1   
1009405             1  2013     1   7           7          2       1   
1008290             1  2013     1   8           8          2       1   
1007175             1  2013     1   9           9          2       1   
1006060             1  2013     1  10          10          2       1   

        is_month_start is_month_end is_quarter_start is_quarter_end  \
1016095              1            0                1              0   
1014980              0            0                0              0   
1013865              0            0                0              0   
1012750              0            0                0              0   
1011635              0            0                0              0   
1010520              0            0                0              0   
1009405              0            0                0              0   
1008290              0            0                0              0   
1007175              0            0                0              0   
1006060              0            0                0              0   

         PromoFirstDate  
1016095               0  
1014980               0  
1013865               0  
1012750               0  
1011635               0  
1010520               0  
1009405               0  
1008290               0  
1007175               0  
1006060               0

In [50]:
# set PromoFirstDate = 1 if Promo = 1 for current row and Promo = 0 for preceding row
train.ix[(train['Promo'] == 1 ) & (train['Promo'].shift(1) ==0), 'PromoFirstDate'] = 1

In [51]:
# glance at data frame to see if this worked correctly
train.head(10)

Store DayOfWeek       Date Sales Customers Open Promo StateHoliday  \
1016095     1         2 2013-01-01     0         0    0     0            a   
1014980     1         3 2013-01-02  5530       668    1     0            0   
1013865     1         4 2013-01-03  4327       578    1     0            0   
1012750     1         5 2013-01-04  4486       619    1     0            0   
1011635     1         6 2013-01-05  4997       635    1     0            0   
1010520     1         7 2013-01-06     0         0    0     0            0   
1009405     1         1 2013-01-07  7176       785    1     1            0   
1008290     1         2 2013-01-08  5580       654    1     1            0   
1007175     1         3 2013-01-09  5471       626    1     1            0   
1006060     1         4 2013-01-10  4892       615    1     1            0   

        SchoolHoliday  year month day day_of_year weekofyear quarter  \
1016095             1  2013     1   1           1          1       1   
1014980             1  2013     1   2           2          1       1   
1013865             1  2013     1   3           3          1       1   
1012750             1  2013     1   4           4          1       1   
1011635             1  2013     1   5           5          1       1   
1010520             1  2013     1   6           6          1       1   
1009405             1  2013     1   7           7          2       1   
1008290             1  2013     1   8           8          2       1   
1007175             1  2013     1   9           9          2       1   
1006060             1  2013     1  10          10          2       1   

        is_month_start is_month_end is_quarter_start is_quarter_end  \
1016095              1            0                1              0   
1014980              0            0                0              0   
1013865              0            0                0              0   
1012750              0            0                0              0   
1011635              0            0                0              0   
1010520              0            0                0              0   
1009405              0            0                0              0   
1008290              0            0                0              0   
1007175              0            0                0              0   
1006060              0            0                0              0   

         PromoFirstDate  
1016095               0  
1014980               0  
1013865               0  
1012750               0  
1011635               0  
1010520               0  
1009405               1  
1008290               0  
1007175               0  
1006060               0

# Examine STORE Data set more carefully

In [60]:
# count number of NaNS
store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [61]:
store.sum()

Store                         622170
CompetitionDistance          6010250
CompetitionOpenSinceMonth       5498
CompetitionOpenSinceYear     1528597
Promo2                           571
Promo2SinceWeek                13473
Promo2SinceYear              1148717
dtype: float64

## Need to determine different methods to deal with Nans

- http://stackoverflow.com/questions/27824954/how-to-handle-missing-nans-for-machine-learning-in-python
- https://www.quora.com/What-are-the-best-ways-to-account-for-missing-data-in-machine-learning
- https://www.kaggle.com/amhchiu/rossmann-store-sales/more-exploratory-data-analysis/notebook

## Store Type

In [63]:
store.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a                 1270                          9   
1      2         a          a                  570                         11   
2      3         a          a                14130                         12   
3      4         c          c                  620                          9   
4      5         a          a                29910                          4   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                      2008       0              NaN              NaN   
1                      2007       1               13             2010   
2                      2006       1               14             2011   
3                      2009       0              NaN              NaN   
4                      2015       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct  
3              NaN  
4              NaN

In [77]:
store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [83]:
pd.unique(store.StoreType.ravel())

array(['c', 'a', 'd', 'b'], dtype=object)

In [84]:
pd.unique(store.CompetitionOpenSinceMonth.ravel())

array([  9.,  11.,  12.,   4.,  10.,   8.,  nan,   3.,   6.,   5.,   1.,
         2.,   7.])

In [85]:
pd.unique(store.CompetitionOpenSinceYear.ravel())

array([ 2008.,  2007.,  2006.,  2009.,  2015.,  2013.,  2014.,  2000.,
        2011.,    nan,  2010.,  2005.,  1999.,  2003.,  2012.,  2004.,
        2002.,  1961.,  1995.,  2001.,  1990.,  1994.,  1900.,  1998.])

In [82]:
store.mean()

Store                         558.000000
CompetitionDistance          5404.901079
CompetitionOpenSinceMonth       7.224704
CompetitionOpenSinceYear     2008.668857
Promo2                          0.512108
Promo2SinceWeek                23.595447
Promo2SinceYear              2011.763573
dtype: float64

**Could set missing CompetitionDistance to mean (5405)**

In [86]:
# join the Train to the Store date frame
train_store = pd.merge(train, store, on='Store')
train_store.head()

Store DayOfWeek       Date Sales Customers Open Promo StateHoliday  \
0     1         2 2013-01-01     0         0    0     0            a   
1     1         3 2013-01-02  5530       668    1     0            0   
2     1         4 2013-01-03  4327       578    1     0            0   
3     1         5 2013-01-04  4486       619    1     0            0   
4     1         6 2013-01-05  4997       635    1     0            0   

  SchoolHoliday  year      ...       PromoFirstDate StoreType Assortment  \
0             1  2013      ...                    0         c          a   
1             1  2013      ...                    0         c          a   
2             1  2013      ...                    0         c          a   
3             1  2013      ...                    0         c          a   
4             1  2013      ...                    0         c          a   

  CompetitionDistance CompetitionOpenSinceMonth CompetitionOpenSinceYear  \
0                1270                         9                     2008   
1                1270                         9                     2008   
2                1270                         9                     2008   
3                1270                         9                     2008   
4                1270                         9                     2008   

  Promo2 Promo2SinceWeek Promo2SinceYear  PromoInterval  
0      0             NaN             NaN            NaN  
1      0             NaN             NaN            NaN  
2      0             NaN             NaN            NaN  
3      0             NaN             NaN            NaN  
4      0             NaN             NaN            NaN  

[5 rows x 29 columns]

In [87]:
train_store.shape

(886103, 29)

In [88]:
# count number of NaNS
train_store.isnull().sum()

Store                             0
DayOfWeek                         0
Date                              0
Sales                             0
Customers                         0
Open                              0
Promo                             0
StateHoliday                      0
SchoolHoliday                     0
year                              0
month                             0
day                               0
day_of_year                       0
weekofyear                        0
quarter                           0
is_month_start                    0
is_month_end                      0
is_quarter_start                  0
is_quarter_end                    0
PromoFirstDate                    0
StoreType                         0
Assortment                        0
CompetitionDistance            2326
CompetitionOpenSinceMonth    281569
CompetitionOpenSinceYear     281569
Promo2                            0
Promo2SinceWeek              439600
Promo2SinceYear             

In [89]:
train_store.sum()

PromoFirstDate                    68625
CompetitionDistance          4792453270
CompetitionOpenSinceMonth       4366776
CompetitionOpenSinceYear     1214317760
Promo2                           446503
Promo2SinceWeek                10432585
Promo2SinceYear               898255049
dtype: float64

In [90]:
train_store.loc[(train['Store'] == 674) &  (train_store['Open'] == 1)]

Store DayOfWeek       Date  Sales Customers Open Promo StateHoliday  \
673        1         6 2015-03-14   5225       599    1     0            0   
1788       3         3 2013-06-12   5520       657    1     0            0   
4018       5         1 2015-06-15   7808       747    1     1            0   
5133       7         5 2013-09-13   9977      1118    1     1            0   
6248       8         2 2014-11-18   5834       766    1     0            0   
7363      10         6 2013-02-16   4340       511    1     0            0   
9593      12         4 2015-02-19   7904       936    1     1            0   
10708     14         3 2013-09-11   5831       666    1     1            0   
12938     17         4 2013-02-14   5804       826    1     0            0   
14053     18         5 2013-12-13   7272       813    1     0            0   
15168     19         2 2015-02-17   7608       748    1     1            0   
16283     21         1 2013-09-09  10531       796    1     1            0   
18513     24         4 2013-06-06   9243       842    1     1            0   
19628     25         1 2014-06-02  16344      1996    1     1            0   
20743     26         2 2015-06-09   5163       453    1     0            0   
21858     28         6 2013-09-07   2371       272    1     0            0   
22973     29         3 2014-11-12   7329       668    1     1            0   
25203     32         1 2013-12-09   4277       575    1     0            0   
27433     35         4 2013-09-05   6160       591    1     0            0   
28548     36         3 2015-03-04  11359      1188    1     1            0   
31893     40         5 2015-06-05   5101       651    1     1            0   
34123     43         1 2015-03-02   9575       791    1     1            0   
35238     45         5 2013-05-31   8104       612    1     1            0   
36353     46         2 2014-05-27   3892       512    1     0            0   
37468     48         1 2013-02-25   3385       440    1     0            0   
38583     49         2 2013-12-24   6422       489    1     0            0   
39698     50         6 2015-02-28   4367       385    1     0            0   
40813     52         5 2013-09-20   6698       481    1     0            0   
41928     53         4 2015-03-19   5793       578    1     1            0   
43043     55         1 2013-06-17   5264       571    1     1            0   
...      ...       ...        ...    ...       ...  ...   ...          ...   
845058  1064         2 2013-07-23   6734       856    1     0            0   
846173  1065         1 2015-01-19   3966       484    1     0            0   
847288  1067         5 2013-04-19   5015       450    1     0            0   
848403  1068         4 2014-10-16   3464       245    1     0            0   
849518  1070         1 2013-01-14   4089       636    1     0            0   
850633  1071         2 2013-11-12   4792       646    1     0            0   
851748  1072         6 2015-01-17   4049       388    1     0            0   
852863  1074         3 2013-04-17   3126       370    1     0            0   
855093  1076         1 2015-04-20   3817       625    1     0            0   
856208  1078         5 2013-07-19   6459       529    1     1            0   
857323  1079         2 2014-07-15  11262       809    1     1            0   
859553  1082         5 2014-04-11   6085       949    1     0            0   
860668  1083         6 2015-04-18   6296       446    1     0            0   
861783  1085         3 2013-07-17   7928       809    1     1            0   
864013  1087         1 2015-07-20   6802       662    1     0            0   
865128  1089         5 2013-10-18   8264       913    1     0            0   
866243  1090         2 2014-12-23  10829      1234    1     0            0   
867358  1092         6 2013-03-23  14081      1276    1     0            0   
868473  1093         5 2014-07-11   7834       847    1     0            0   
869588  1095         4 2013-0